version: "3.9"

services:
  dev:
    image: nindo:base
    build: .
    command: /bin/sh
    tty: yes
  storybook:
    image: nindo:base  
    working_dir: /app/packages/storybook
    command: yarn dev

